excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://areff2000.github.io
title: Resbaz, SciHackMelb 2016; Plot.ly, D3, other datavis...
tagline: Interactive Visualisation 
description: My awesome new site/#datavis
paginate: 5
