excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://areff2000.github.io
title: Resbaz 2016; Plot.ly test (rf)
tagline: Interactive Visualisation 
description: My awesome new site/#datavis
paginate: 5
