excerpt_separator: ""
highlighter: rouge
// pygments: true
markdown: kramdown
url: http://areff2000.github.io
title: Resbaz 2016-18; Plot.ly, D3, other datavis...
tagline: Interactive Visualisation 
description: My exploring datavis | <a href="https://figshare.com/authors/Richard_Ferrers/401493">My data</a>
paginate: 5
