excerpt_separator: ""
highlighter: rouge
// pygments: true
markdown: kramdown
url: http://areff2000.github.io
title: Resbaz, SciHackM 2016; Plot.ly, D3, other datavis...
tagline: Interactive Visualisation 
description: My exploring #datavis
paginate: 5
